version: '3'
services:
  ros2:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: ros2
    user: ubuntu
    group_add:
      - dialout
      - tty
      - messagebus
      - video
    volumes:
      - ../:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/:/dev/
      - /run/udev:/run/udev
      - /run/dbus:/run/dbus

    network_mode: host
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_SERVER
    ports:
      - 5000:5000
    devices:
      - /dev/ttyS0:/dev/ttyS0
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/i2c-1:/dev/i2c-1
      - /dev/i2c-0:/dev/i2c-0
      - /dev/input/:/dev/input/
      - /dev/media0:/dev/media0
      - /dev/media1:/dev/media1
      - /dev/media2:/dev/media2
      - /dev/media3:/dev/media3
      - /dev/media4:/dev/media4

      - /dev/v4l-subdev0:/dev/v4l-subdev0
      - /dev/video0:/dev/video0
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/video13:/dev/video13
      - /dev/video14:/dev/video14
      - /dev/video15:/dev/video15
      - /dev/video16:/dev/video16
      - /dev/video18:/dev/video18
      - /dev/video19:/dev/video19
      - /dev/video20:/dev/video20
      - /dev/video21:/dev/video21
      - /dev/video22:/dev/video22
      - /dev/video23:/dev/video23
      - /dev/video31:/dev/video31
    command: /bin/sh -c "while sleep 1000; do :; done"
